wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
    t:
      1:
      - 1
      - 3
      - 5
      - 9
      2:
      - 1
      - 3
      - 5
      - 9
      4: 3.7.4
      5: 0.10.22
      8:
      - 3
      - 5
architecture:
  desc: null
  value: RegressionModel
batch_size:
  desc: null
  value: 128
dataset:
  desc: null
  value: adult
disable_dp:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.1
n_epoch:
  desc: null
  value: 2
run_name:
  desc: null
  value: adult-DP_SGD-edu-15
sigma(noise):
  desc: null
  value: 1.0
